import Head from "next/head";
import Image from "next/image";
import Sidebar from "../components/Sidebar";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Tap-2-Reach | Keeping Your Customers Close</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                {/* TODO:  Add keywords Meta tag*/}
                <link rel="icon" href="/favicon.ico" />
                <link rel="apple-touch-icon" href="/logo192.png" />
            </Head>

            <Sidebar />
        </div>
    );
}
